//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUCera {
	
	
	public partial class Login {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox username;
		
		protected System.Web.UI.WebControls.TextBox password;
		
		protected System.Web.UI.WebControls.Button loginbutton;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton1;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton2;
		
		protected System.Web.UI.WebControls.LinkButton LinkButton3;
	}
}
